name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 18765'
        src: 'public/'
        dest: 'kwiksher@kwiksher.com:/home/kwiksher/public_html/storyboard-editor/doc'
    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}" 
